### ISSUE TITLE
add hear support

### ISSUE THREAD

**Issue by rompic** [robhurring/hubot-redmine#22]
why was the hear support dropped?
https://github.com/github/hubot-scripts/blob/master/src/scripts/redmine.coffee

**Comment by stephenyeargin** [comment]
Looking through the history of this package, it doesn't appear that the `hear` feature was part of it when moved into its own node module.

From a practical standpoint, using `hear` can be a bad idea for anything other than novelty scripts. I say that because there is a high chance that two packages will register commands that respond to the same block of text, or a user will get confusing output when not talking to the bot (e.g. "We were #53 in line to see Star Wars" would trigger a link to Redmine issue 35.). It is better to talk directly to the bot if you need something from it.

If you would like to restore the support for your particular use case, copying the file directly into your `/scripts` folder and adding that command back should work. But for this package's purpose, I don't see it coming back.

**Comment by rompic** [comment]
makes sense.
